name: Scheduled Bot Execution

on:
  schedule:
    # Run every 4 hours
    - cron: '0 */4 * * *'

jobs:
  run-bot:
    name: Execute Bot
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run bot
      env:
        ORACLE_FRESHNESS_IN_SECONDS: 43200 # 12 hours
        TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
        TELEGRAM_GROUP_CHAT_ID: ${{ secrets.TELEGRAM_GROUP_CHAT_ID }}
      run: |
        python ./src/main.py
