name: Validate Config

on:
  push:
    paths:
      - 'config.json'
      - 'abi/**'
      - '.github/workflows/validate-config.yml'

jobs:
  config-validation:
    name: Config Validation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Validate configuration
      env:
        SAFE_ADDRESS: ${{ vars.SAFE_ADDRESS }}
        FRAX_SAFE_ADDRESS: ${{ vars.FRAX_SAFE_ADDRESS }}
        LISK_SAFE_ADDRESS: ${{ vars.LISK_SAFE_ADDRESS }}
      run: |
        echo "SAFE_ADDRESS=$SAFE_ADDRESS"
        echo "FRAX_SAFE_ADDRESS=$FRAX_SAFE_ADDRESS"
        echo "LISK_SAFE_ADDRESS=$LISK_SAFE_ADDRESS"
        python ./src/config/validate_config.py
