name: Validate Config

on:
  push:
    paths:
      - 'config.json'
      - 'abi/**'
      - '.github/workflows/validate-config.yml'

jobs:
  config-validation:
    name: Config Validation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Validate configuration
      run: python ./src/config/validate_config.py
